Task
sol1corejz/goferrrmart pull request #1
Opened 2024-10-21 18:38 UTC by sol1corejz

2024-10-21 18:50 UTC, sol1corejz commented
падают ошибки в тестах на вывод средст, локально делаю запросы все хорошо, но в тестах заметил, что постится ордер с одним номером, а вывести уже пытаемся с другим номером, поэтому в бд невозможно найти запись c передаваемым номером

может я что-то не так понимаю, помогите пожалуйста

2024-10-28 06:57 UTC, aggrofreakazoid requested changes

2024-10-28 06:57 UTC, aggrofreakazoid commented on internal/handlers/postOrder.go
> +		resp, err := http.Post("http://localhost:8080/api/orders", "application/json", bytes.NewBuffer(jsonData))
лучше не оставлять захардкоженные адреса в коде. и вообще строки выводить в константы вверху go-файла лучше - чтобы была возможность сразу увидеть

2024-10-28 06:57 UTC, aggrofreakazoid commented on internal/middleware/authMiddleware.go
> +	isValid := tokenstorage.CheckToken(token)
странная проверка токена. То есть если у нас будет 2 пользователя в системе - они не смогут одновременно быть залогиненными из-за того что в модуле tokenstorage глобальная переменная token?

2024-11-04 18:43 UTC, aggrofreakazoid approved these changes

2024-11-04 20:42 UTC, merged